
export const RIVER_STATIONS = {
  YUMW1: {
    id: 'YUMW1',
    label: 'Yakima - At Cle Elum',
    riverId: 'yakima',
    riverName: 'Yakima River',
    lat: 47.1917,
    lng: -120.9456,
  },
  HLKW1: {
    id: 'HLKW1',
    label: 'Yakima - Near Horlick',
    riverId: 'yakima',
    riverName: 'Yakima River',
    lat: 47.1242,
    lng: -120.7392,
  },
  TNAW1: {
    id: 'TNAW1',
    label: 'Teanaway - Below Forks',
    riverId: 'yakima',
    riverName: 'Yakima River',
    lat: 47.2461,
    lng: -120.8611,
  },
  EASW1: {
    id: 'EASW1',
    label: 'Yakima - At Eason',
    riverId: 'yakima',
    riverName: 'Yakima River',
    lat: 47.2389,
    lng: -121.1778,
  },
  UMTW1: {
    id: 'UMTW1',
    label: 'Yakima - At Umtanum',
    riverId: 'yakima',
    riverName: 'Yakima River',
    lat: 46.8628,
    lng: -120.4789,
  },
  CONW1: {
    id: 'CONW1',
    label: 'Skagit - Near Concrete',
    riverId: 'skagit',
    riverName: 'Skagit River Basin',
    lat: 48.5244,
    lng: -121.7697,
  },
  MVEW1: {
    id: 'MVEW1',
    label: 'Skagit - Near Mt. Vernon',
    riverId: 'skagit',
    riverName: 'Skagit River Basin',
    lat: 48.4450,
    lng: -122.3342,
  },
  SRMW1: {
    id: 'SRMW1',
    label: 'Cascade - At Marblemount',
    riverId: 'skagit',
    riverName: 'Skagit River Basin',
    lat: 48.5339,
    lng: -121.429,
  },
  GORW1: {
    id: 'GORW1',
    label: 'Skagit - At Newhalem',
    riverId: 'skagit',
    riverName: 'Skagit River Basin',
    lat: 48.6667,
    lng: -121.2500,
  },
  GORW1: {
    id: 'GORW1',
    label: 'Green - Below Howard Hanson Dam',
    riverId: 'green',
    riverName: 'Green River',
    lat: 47.2836,
    lng: -121.7967,
  },
  AUBW1: {
    id: 'AUBW1',
    label: 'Green - Near Auburn',
    riverId: 'green',
    riverName: 'Green River',
    lat: 47.3128,
    lng: -122.2036,
  },
  GPUW1: {
    id: 'GPUW1',
    label: 'Green - Near Palmer',
    riverId: 'green',
    riverName: 'Green River',
    lat: 47.3000,
    lng: -121.8500,
  },
  LNDW1: {
    id: 'LNDW1',
    label: 'Cedar - Near Landsburg',
    riverId: 'cedar',
    riverName: 'Cedar River',
    lat: 47.4000,
    lng: -121.9500,
  },
  RNTW1: {
    id: 'RNTW1',
    label: 'Cedar - At Renton',
    riverId: 'cedar',
    riverName: 'Cedar River',
    lat: 47.4828,
    lng: -122.2019,
  },
  GLBW1: {
    id: 'GLBW1',
    label: 'Skykomish - Near Gold Bar',
    riverId: 'skykomish',
    riverName: 'Skykomish River',
    lat: 47.8353,
    lng: -121.6600,
  },
  ARLW1: {
    id: 'ARLW1',
    label: 'Stillaguamish - Near Arlington',
    riverId: 'stillaguamish',
    riverName: 'Stillaguamish River',
    lat: 48.2036,
    lng: -122.1281
  },
  ARGW1: {
    id: 'ARGW1',
    label: 'NF Stillaguamish - Near Arlington',
    riverId: 'stillaguamish',
    riverName: 'Stillaguamish River',
    lat: 48.2606,
    lng: -122.0475
  },
  SSFW1: {
    id: 'SSFW1',
    label: 'SF Stillaguamish - At Jordan Road',
    riverId: 'stillaguamish',
    riverName: 'Stillaguamish River',
    lat: 48.0953,
    lng: -121.9742
  },
}