import { FISH } from './fish'
import { RIVER_TYPES } from './riverTypes'
import { RIVER_STATIONS } from './riverStations'

// https://www.nwrfc.noaa.gov/rfc/

export const RIVERS = [
  {
    id: 'yakima',
    name: 'Yakima River',
    state: 'WA',
    lat: 46.8581,
    lng: -120.5059,
    image: require('@assets/images/yakima-detail.png'),
    subImage: require('@assets/images/yakima-background.png'),
    description: 'The Yakima cuts through a steep basalt canyon in central Washington, fed by the eastern slopes of the Cascades.',
    type: [RIVER_TYPES.tailwater, RIVER_TYPES.freestone],
    fish: [FISH.rainbow_trout, FISH.brown_trout],
    stations: [RIVER_STATIONS.EASW1, RIVER_STATIONS.YUMW1, RIVER_STATIONS.TNAW1, RIVER_STATIONS.HLKW1, RIVER_STATIONS.UMTW1],
  },
  {
    id: 'skagit',
    name: 'Skagit River Basin',
    state: 'WA',
    lat: 48.4450,
    lng: -122.334,
    image: require('@assets/images/skagit-detail.png'),
    subImage: require('@assets/images/skagit-background.png'),
    description: 'A major river draining the North Cascades of northwest Washington, running from the high peaks through old growth valleys to Puget Sound.',
    type: [],
    fish: [],
    stations: [RIVER_STATIONS.CONW1, RIVER_STATIONS.MVEW1, RIVER_STATIONS.SRMW1, RIVER_STATIONS.GORW1],
  },
  {
    id: 'green',
    name: 'Green River',
    state: 'WA',
    lat: 47.3128,
    lng: -122.2036,
    image: require('@assets/images/green-detail.png'),
    subImage: require('@assets/images/green-background.png'),
    description: 'The Green flows out of Howard Hanson Dam through the foothills southeast of Seattle before winding into the lowlands of King County.',
    type: [],
    fish: [],
    stations: [RIVER_STATIONS.GORW1, RIVER_STATIONS.AUBW1, RIVER_STATIONS.GPUW1],
  },
  {
    id: 'cedar',
    name: 'Cedar River',
    state: 'WA',
    lat: 47.5007,
    lng: -122.2162,
    image: require('@assets/images/cedar-detail.png'),
    subImage: require('@assets/images/cedar-background.png'),
    description: 'The Cedar drains the Cascade foothills southeast of Seattle, flowing through Renton before emptying into Lake Washington.',
    type: [],
    fish: [],
    stations: [RIVER_STATIONS.LNDW1, RIVER_STATIONS.RNTW1],
  },
  {
    id: 'skykomish',
    name: 'Skykomish River',
    state: 'WA',
    lat: 47.8370,
    lng: -121.6670,
    image: require('@assets/images/skykomish-detail.png'),
    subImage: require('@assets/images/skykomish-background.png'),
    description: 'The Skykomish drains the western slopes of the Cascades through the towns of Index and Sultan before joining the Snoqualmie to form the Snohomish River near Monroe.',
    type: [],
    fish: [],
    stations: [RIVER_STATIONS.GLBW1],
  },
  {
    id: 'stillaguamish',
    name: 'Stillaguamish River',
    state: 'WA',
    lat: 48.2606,
    lng: -122.0475,
    image: require('@assets/images/stillaguamish-detail.png'),
    subImage: require('@assets/images/stillaguamish-background.png'),
    description: 'The Stillaguamish flows out of the Cascades through Arlington and Stanwood before reaching Port Susan Bay on Puget Sound.',
    type: [],
    fish: [],
    stations: [RIVER_STATIONS.ARLW1, RIVER_STATIONS.ARGW1, RIVER_STATIONS.SSFW1],
  },
]