export const STATIONS = {
  YUMW1: {
    id: 'YUMW1',
    label: 'Yakima - At Cle Elum',
    riverId: 'yakima',
    riverName: 'Yakima River',
    lat: 47.1917,
    lng: -120.9456,
  },
  HLKW1: {
    id: 'HLKW1',
    label: 'Yakima - Near Horlick',
    riverId: 'yakima',
    riverName: 'Yakima River',
    lat: 47.1242,
    lng: -120.7392,
  },
  TNAW1: {
    id: 'TNAW1',
    label: 'Teanaway - Below Forks',
    riverId: 'yakima',
    riverName: 'Yakima River',
    lat: 47.2461,
    lng: -120.8611,
  },
  EASW1: {
    id: 'EASW1',
    label: 'Yakima - At Eason',
    riverId: 'yakima',
    riverName: 'Yakima River',
    lat: 47.2389,
    lng: -121.1778,
  },
  UMTW1: {
    id: 'UMTW1',
    label: 'Yakima - At Umtanum',
    riverId: 'yakima',
    riverName: 'Yakima River',
    lat: 46.8628,
    lng: -120.4789,
  },
}