export const TIDAL_STATIONS = [
  {
    id: '9444900',
    name: 'Port Townsend',
    state: 'WA',
    location: 'Jefferson County, Strait of Juan de Fuca',
    lat: 48.1117,
    lng: -122.7600,
    image: require('@assets/images/port-townsend-station-detail.png'),
    howToReach: 'Located at the Washington State Ferries dock on Water Street near Point Hudson.',
  },
  {
    id: '9447659',
    name: 'Everett',
    state: 'WA',
    location: 'Snohomish County, Port Gardner Bay',
    lat: 47.9800,
    lng: -122.2233,
    image: require('@assets/images/everett-detail.png'),
    howToReach: 'Located at the Port of Everett Pier 1 on the west end of Terminal Street.',
  },
  {
    id: '9447427',
    name: 'Edmonds',
    state: 'WA',
    location: 'Snohomish County, Puget Sound',
    lat: 47.8133,
    lng: -122.3833,
    image: require('@assets/images/edmonds-detail.png'),
    howToReach: 'Located at the west end of the Washington State Ferry pier at Main Street.',
  },
  {
    id: '9447130',
    name: 'Seattle',
    state: 'WA',
    location: 'King County, Elliott Bay',
    lat: 47.8133,
    lng: -122.3833,
    image: require('@assets/images/seattle-station-detail.png'),
    howToReach: 'Located in the Bremerton Ferry terminal building at Slip 2 on Alaskan Way.',
  },
  {
    id: '9445958',
    name: 'Bremerton',
    state: 'WA',
    location: 'Kitsap County, Sinclair Inlet',
    lat: 47.5617,
    lng: -122.6233,
    image: require('@assets/images/bremerton-station-detail.png'),
    howToReach: 'Located at the Washington State Ferry Terminal on Pacific Ave.',
  },
  {
    id: '9446484',
    name: 'Tacoma',
    state: 'WA',
    location: 'Pierce County, Commencement Bay',
    lat: 47.2667,
    lng: -122.4133,
    image: require('@assets/images/tacoma-station-detail.png'),
    howToReach: 'Located on the north side of the Port of Tacoma Administration Building at Pier 7.',
  },
  {
    id: '9446375',
    name: 'Tahlequah',
    state: 'WA',
    location: 'Pierce County, Vashon Island',
    lat: 47.3333,
    lng: -122.5067,
    image: require('@assets/images/tahlequah-detail.png'),
    howToReach: 'Located at the Tahlequah ferry terminal on the south end of Vashon Island.',
  },
  {
    id: '9446500',
    name: 'Home, Puget Sound',
    state: 'WA',
    location: 'Pierce County, Case Inlet',
    lat: 47.2750,
    lng: -122.7583,
    image: require('@assets/images/puget-sound-detail.png'),
    howToReach: 'No published directions available for this station.',
  },
  {
    id: '9446254',
    name: 'Burton',
    state: 'WA',
    location: 'King County, Quartermaster Harbor',
    lat: 47.3950,
    lng: -122.4633,
    image: require('@assets/images/burton-detail.png'),
    howToReach: 'No published directions available for this station.',
  },
]