export const SPONSOR_LOGOS = {
    'hoopfest-store.png': require('@assets/sponsors/hoopfest-store.png'),
    'ten_capital.png': require('@assets/sponsors/ten-capital.png'),
    'toyota_shootoff.png': require('@assets/sponsors/toyota-shootoff.png'),
    'player_change.png': require('@assets/sponsors/player-change.png'),
    'amazon.png': require('@assets/sponsors/amazon.png'),
    'rodda_paint.png': require('@assets/sponsors/rodda-paint.png'),
    'guardian.png': require('@assets/sponsors/guardian.png'),
    'numerica.png': require('@assets/sponsors/numerica.png'),
    'multicare.png': require('@assets/sponsors/multicare.png'),
    'gesa.png': require('@assets/sponsors/gesa.png'),
    'nq.png': require('@assets/sponsors/northern-quest-dark.png'),
    'wssg.png': require('@assets/sponsors/wssg.png'),
    'xfinity.png': require('@assets/sponsors/xfinity.png'),
    'takis.png': require('@assets/sponsors/takis.png'),
    'UI_stacked.png': require('@assets/sponsors/ui-stacked.png'),
    'Verizon.png': require('@assets/sponsors/verizon.png'),
    'htx.png': require('@assets/sponsors/htx.png'),
    'Country-Financial.png': require('@assets/sponsors/country-financial.png'),
    '24-HR-Event-Embrace-Hoopfest-Logo-2025.png': require('@assets/sponsors/embrace-hoopfest.png'),
    'delta-air-lines.png': require('@assets/sponsors/delta-airlines.png'),
    'ICCU.png': require('@assets/sponsors/iccu.png'),
    'US-Bank.png': require('@assets/sponsors/us-bank.png'),
    'Baden.png': require('@assets/sponsors/baden.png'),
    'First-interstate-bank.png': require('@assets/sponsors/first-interstate-bank.png'),
}